# Generated by Django 2.2.1 on 2020-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_havn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favorite_article',
            field=models.ManyToManyField(blank=True, related_name='favorite_article', to='gamers_havn.Article'),
        ),
        migrations.AlterField(
            model_name='account',
            name='followed_game',
            field=models.ManyToManyField(blank=True, related_name='followed_game', to='gamers_havn.Game'),
        ),
    ]
