# Generated by Django 2.2.1 on 2020-03-17 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_havn', '0004_auto_20200316_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 15, 13, 14, 799474, tzinfo=utc)),
        ),
    ]
