# Generated by Django 2.2.1 on 2020-03-17 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_havn', '0006_auto_20200317_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 17, 10, 10, 39150, tzinfo=utc), editable=False),
        ),
    ]
