# Generated by Django 2.2.1 on 2020-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_havn', '0011_auto_20200321_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portrait',
            field=models.ImageField(default='D:\\_Coding\\Course\\IT\\team_project\\IT_Team_Project\\staticimages/user_default.png', upload_to='profile_images'),
        ),
    ]
