# Generated by Django 2.2.1 on 2020-03-22 16:40

from django.db import migrations, models
import gamers_havn.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_havn', '0012_auto_20200322_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portrait',
            field=models.ImageField(default='D:\\_Coding\\Course\\IT\\team_project\\IT_Team_Project\\static\\images\\user_default.png', upload_to=gamers_havn.models.PathAndRename('profile_images')),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.FileField(upload_to=gamers_havn.models.PathAndRename('articles')),
        ),
    ]
