# Generated by Django 2.2.1 on 2020-03-22 23:33

from django.db import migrations, models
import gamers_havn.models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_havn', '0013_auto_20200322_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portrait',
            field=models.ImageField(blank=True, upload_to=gamers_havn.models.PathAndRename('profile_images')),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
