# Generated by Django 2.2.1 on 2020-03-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers_havn', '0015_auto_20200322_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
